fix: tests

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -40,3 +40,37 @@ jobs:
             echo "POST test failed with status code $POST_STATUS_CODE"
             exit 1
           fi
+
+          # Prueba método GET. Debe retornar un status code 405 (se envía PAYLOAD cuando no lo acepta).
+          echo "Invoking GET method"
+          RESPONSE_GET=$(aws lambda invoke --function-name $LAMBDA_FUNCTION_NAME --payload '{}' response_get.json)
+          GET_STATUS_CODE=$(cat response_get.json | jq -r '.statusCode')
+          if [[ "$GET_STATUS_CODE" -eq 405 ]]; then
+            echo "GET test with payload passed"
+          else
+            echo "GET test with payload failed with status code $GET_STATUS_CODE"
+            exit 1
+          fi
+
+          # Prueba del método POST. Debe retornar un status code 405 (no mandamos payload).
+          echo "Invoking POST method without payload"
+          RESPONSE_POST=$(aws lambda invoke --function-name $LAMBDA_FUNCTION_NAME response_post.json)
+          POST_STATUS_CODE=$(cat response_post.json | jq -r '.statusCode')
+          if [[ "$POST_STATUS_CODE" -eq 405 ]]; then
+            echo "POST test without payload passed"
+          else
+            echo "POST test without payload failed with status code $POST_STATUS_CODE"
+            exit 1
+          fi
+
+          # Prueba del método POST. Debe retornar un status code 405 (mandamos payload incorrecto).
+          echo "Invoking POST method"
+          POST_PAYLOAD='{ "nome": "Juan Perez", "correo": "juan.perez@latam.com" }'
+          RESPONSE_POST=$(aws lambda invoke --function-name $LAMBDA_FUNCTION_NAME --payload "$POST_PAYLOAD" response_post.json)
+          POST_STATUS_CODE=$(cat response_post.json | jq -r '.statusCode')
+          if [[ "$POST_STATUS_CODE" -eq 400 ]]; then
+            echo "POST test with incorrect payload passed"
+          else
+            echo "POST test with incorrect payload failed with status code $POST_STATUS_CODE"
+            exit 1
+          fi          
